{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qcap-registry.secretName" . }}
  labels:
    {{- include "qcap-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
